### ISSUE TITLE
1.19 startup issue

### ISSUE THREAD

**Issue by mrfloris** [herby2212/FakePlayers#1]
```
[08:32:03 INFO]: [FakePlayers] Enabling FakePlayers v2.4*
[08:32:03 INFO]:
[08:32:03 INFO]: =====>[FakePlayers Terms]<=====
[08:32:03 INFO]: -> You are not permitted to claim this plugin as your own!
[08:32:03 INFO]: -> You are not permitted to decompiling the plugin's sourcecode!
[08:32:03 INFO]: -> You are not permitted to modify the code or the plugin and call it your own!
[08:32:03 INFO]: -> You are not permitted to redistributing this plugin as your own!
[08:32:03 INFO]: ======>[Terms Accepted!]<======
[08:32:03 INFO]:
[08:32:03 ERROR]: Error occurred while enabling FakePlayers v2.4 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?]
	at de.Herbystar.FakePlayers.CustomPlayer.NMS_CustomPlayer.<init>(NMS_CustomPlayer.java:114) ~[FakePlayers-2.4.jar:?]
	at de.Herbystar.FakePlayers.PlayerListHandler.NMS_PlayerListHandler.setOnlinePlayers(NMS_PlayerListHandler.java:113) ~[FakePlayers-2.4.jar:?]
	at de.Herbystar.FakePlayers.Main.setFakePlayers(Main.java:96) ~[FakePlayers-2.4.jar:?]
	at de.Herbystar.FakePlayers.Main.onEnable(Main.java:67) ~[FakePlayers-2.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:554) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:468) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[08:32:03 INFO]: [FakePlayers] Disabling FakePlayers v2.4
[08:32:03 INFO]: [FakePlayers] Version: 2.4 by [Herbystar] disabled!
```
```
> ver tta
[08:32:59 INFO]: TTA version 5.4
[08:32:59 INFO]: Title, Tablist, ActionBar, BossBar, Holo, Ping, Glow API!
[08:32:59 INFO]: Website: https://github.com/herby2212/TTA
[08:32:59 INFO]: Author: Herbystar
> ver
[08:33:00 INFO]: Checking version, please wait...
[08:33:01 INFO]: This server is running Paper version git-Paper-"9b6fb2f" (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 9b6fb2f on dev/1.19)
Error obtaining version information
Previous version: git-Paper-"02b5ec4" (MC: 1.19)
> ver FakePlayers
[08:33:03 INFO]: FakePlayers version 2.4
[08:33:03 INFO]: A plugin to manipulate the online count!
[08:33:03 INFO]: Author: Herbystar
>
```

**Comment by herby2212** [comment]
Please check that the `defaultWorld` in your config is set correctly. To the name of the world folder.

**Comment by mrfloris** [comment]
Yep, that was it. okay, updated my friends test server, we can start debugging the /list issue he has again. tnx for the response.
