### ISSUE TITLE
Fake players are being kick with essentials even when permissions are given to stop it

### ISSUE THREAD

**Issue by Josh65-2201** [herby2212/FakePlayers#19]
No idea if it this plugin or [essentials](https://github.com/EssentialsX/Essentials) but with lucky perms I have given the fake player permissions to not be kicked when idle but it still does. I have tested this with me and I don't get kicked as expected.

```
[16:32:25 INFO]: server lost connection: You have been kicked for idling more than 15 minutes.
[16:32:25 WARN]: [Essentials] EssentialsTimer Error:
java.lang.NullPointerException: Cannot invoke "io.netty.channel.ChannelConfig.setAutoRead(boolean)" because the return value of "io.netty.channel.Channel.config()" is null
        at net.minecraft.network.Connection.setReadOnly(Connection.java:717) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:459) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:421) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftPlayer.kickPlayer(CraftPlayer.java:523) ~[paper-1.18.2.jar:git-Paper-387]
        at com.earth2me.essentials.User.checkActivity(User.java:832) ~[EssentialsX-2.20.0-dev+15-20011b9.jar:?]
        at com.earth2me.essentials.EssentialsTimer.run(EssentialsTimer.java:64) ~[EssentialsX-2.20.0-dev+15-20011b9.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by herby2212** [comment]
Thanks for the report.
It seems that essentials is trying a logic part that the faked player currently doesn't have. 
Does this error also appear with the FakePlayers 2.8-SNAPSHOT (https://github.com/herby2212/FakePlayers/releases/tag/2.8-SNAPSHOT) build?

**Comment by Josh65-2201** [comment]
Yes. I did try that

**Comment by herby2212** [comment]
Ok. Essentials is trying to use a part of the faked player that they currently don't have. I aim to fix it with the full 2.8 release.
