### ISSUE TITLE
Help me 

### ISSUE THREAD

**Issue by Minecraft7198** [herby2212/FakePlayers#25]
08:04:31 ERROR: Error occurred while enabling FakePlayers v2.7 (Is it up to date?) java.lang.NoClassDefFoundError: de/lierbystar/TTA/Utils/Reflection at de Herbystar. FakePlayers PlayerListHandler.MUS Player ListHandler.<clinit>(NMS_PlayerListHandler.java:59) [Ful

-2.7.jar:71 at de Herbystar FakePlayers Nain.initializePlayert istHandler(Main.java:134)-[FakePlayers-2.7.jar:21

at de Herbystar, FakePlayers.Main.onEnable(Main.java:55) [FakePlayers-2.7.jar:71 at org.bukkit.plugin.java. JavaPlugin.setEnabled( JavaPlugin java:281) [paper-apt-1,19.4 R0.1-SNAPSHOT.jar:?]|

at to paperne paper.plugin.manager. PaperPluginInstancellanager.enablePlugin(PaperPluginInstanceManager.java:189 .19.4.jar:git-Paper-5381 at 30 paperne paper.plugin.manager. PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) -[paper- r:git-Paper-538]

) -

at org.bukkit.plugin, SimplePluginManager.enablePlugin(SimplePluginManager.java:507) [paper ap: 1.19.4-80.1-SNAP:

at org.bukkit.craftbukkit.v1_19_R3. CraftServer.enablePlugin(CraftServer.java:556)-[paper-1.19.4.jar:git Paper-S at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins (CraftServer.java:467) [paper-1.19.4.jar:git-Paper- at net.minecraft.server.MinecraftServer, loadworldo(MinecraftServer.java:638) -paper-1.19.4.jar:git-Paper-5381

at net.minecraft.server.MinecraftServer. loadLevel (MinecraftServer.java:437) [paper-1.19.4.jar:git-Paper-538]

at net.minecraft.server.dedicated. DedicatedServer. initServer (DedicatedServer.java:308) [paper-1.19.4.jar:git-Poj

at net.minecraft.server.MinecraftServer.runServer (MinecraftServer.java:1104) [paper-1.19.4.jar:git-Paper-538]

at net.minecraft.server.MinecraftServer.lambda$spins0(MinecraftServer.java:320) -[paper-1.19.4.jar:git-Paper-538

at java.lang.Thread.run(Thread.java:33) 17:23

Caused by: java.lang.ClassNotFoundException: de Herbystar TTA Utils. Reflection

at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:183) -paper-api-1.19.4-RO. 1-SNAPSI

1 at org.bukkit.plugin, java.PluginClassLoader.loadClass(PluginClassLoader.java:150)-[paper-api-1.19.4-RO.1-SNAPSH at java.lang.ClassLoader.loadClass(ClassLoader.java:520) 17:71 15 more

[08:04:31 INFO]: [FakePlayers] Disabling FakePlayers v2.7

[08:04:31 ERROR: Error occurred (in the plugin loader) while disabling FakePlayers v2.7 (Is it up to date?)

java.lang.NullPointerException: Cannot Lavuke "de.Herbystor. FakePlayers. Player ListHandler.PlayerListHandler.removeonlinel

**Comment by Gudong-laile** [comment]
this plugin still doesn't support 1.19.4.

**Comment by Gudong-laile** [comment]
![image](https://github.com/herby2212/FakePlayers/assets/118879610/f7997d06-16cb-4d3c-ae47-9304630670ec)
the latest version only support to 1.19.2.
Hope our dear herby2212 update it QAQ

**Comment by pollywantza** [comment]
Please update!
